/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package high_school;

import javax.swing.JOptionPane;

/**
 *
 * @author Adrian
 */
public class GradeEntry extends javax.swing.JPanel {

    /**
     * Creates new form GradeEntry
     */
    public GradeEntry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfd_id = new javax.swing.JTextField();
        lab_student = new javax.swing.JLabel();
        lab_student1 = new javax.swing.JLabel();
        tfd_grade = new javax.swing.JTextField();
        tfd_sid1 = new javax.swing.JTextField();
        lab_student2 = new javax.swing.JLabel();
        btn_upload = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(600, 440));
        setMinimumSize(new java.awt.Dimension(600, 440));
        setPreferredSize(new java.awt.Dimension(600, 440));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setMaximumSize(new java.awt.Dimension(600, 60));
        jPanel2.setMinimumSize(new java.awt.Dimension(600, 60));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Student Enrollment History");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tfd_id.setMaximumSize(new java.awt.Dimension(80, 20));
        tfd_id.setMinimumSize(new java.awt.Dimension(80, 20));
        tfd_id.setPreferredSize(new java.awt.Dimension(80, 20));
        tfd_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_idActionPerformed(evt);
            }
        });

        lab_student.setBackground(new java.awt.Color(204, 204, 255));
        lab_student.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_student.setText("Enter Grade");
        lab_student.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_student.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_student.setPreferredSize(new java.awt.Dimension(80, 30));

        lab_student1.setBackground(new java.awt.Color(204, 204, 255));
        lab_student1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_student1.setText("Section id");
        lab_student1.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_student1.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_student1.setPreferredSize(new java.awt.Dimension(80, 30));

        tfd_grade.setMaximumSize(new java.awt.Dimension(80, 20));
        tfd_grade.setMinimumSize(new java.awt.Dimension(80, 20));
        tfd_grade.setPreferredSize(new java.awt.Dimension(80, 20));
        tfd_grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_gradeActionPerformed(evt);
            }
        });

        tfd_sid1.setMaximumSize(new java.awt.Dimension(80, 20));
        tfd_sid1.setMinimumSize(new java.awt.Dimension(80, 20));
        tfd_sid1.setPreferredSize(new java.awt.Dimension(80, 20));
        tfd_sid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_sid1ActionPerformed(evt);
            }
        });

        lab_student2.setBackground(new java.awt.Color(204, 204, 255));
        lab_student2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_student2.setText("Student Id");
        lab_student2.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_student2.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_student2.setPreferredSize(new java.awt.Dimension(80, 30));

        btn_upload.setText("Upload grade");
        btn_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lab_student1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lab_student, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfd_grade, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd_id, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(tfd_sid1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(btn_upload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(lab_student2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(503, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(tfd_id, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_student1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd_sid1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_student, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd_grade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_upload)
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(lab_student2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(282, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String grades(){
        String id= tfd_id.getText();
        String section= tfd_sid1.getText();
        
        boolean sec=false, stu=false;
        
        double grade= Double.parseDouble(tfd_grade.getText());
        if(grade<0 || grade>100)  return "invalid grade entered";
        
        
        int i;
        int x;
        //searching for valid id
      
        for(i=0; i<Highschool.student_arr.length;i++){
            if(Highschool.student_arr[i]==null);
            else{
              if(Highschool.student_arr[i].getID().equals(id)){  
                stu=true;
                  break;}}
                  } 
                
         if (stu==false)return "Invalid Student Id";
         else{
             for(x=0; x<Highschool.student_arr[i].getEnrollHist().length;x++){
                   if(Highschool.student_arr[i].getEnrollHist()[x] ==null);
                   
                   else{
                       if(Highschool.student_arr[i].getEnrollHist()[x].getCourse().getSectionId().equals(section)){
                           sec=true;break;}}
             }
            }   
         
         if(sec==false)return "Student isnt enrolled into this course"; 
                         
         else{
             Highschool.student_arr[i].getEnrollHist()[x].setGrade(grade);
             return "Student grade sucessfully updated";
         }
           
}   
    
    private void tfd_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_idActionPerformed

    private void tfd_gradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_gradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_gradeActionPerformed

    private void tfd_sid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_sid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_sid1ActionPerformed

    private void btn_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uploadActionPerformed
        String grade= grades();
        JOptionPane.showMessageDialog(this,grade);     
        tfd_grade.setText("");
        tfd_id.setText("");
        tfd_sid1.setText("");
    }//GEN-LAST:event_btn_uploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_upload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lab_student;
    private javax.swing.JLabel lab_student1;
    private javax.swing.JLabel lab_student2;
    private javax.swing.JTextField tfd_grade;
    private javax.swing.JTextField tfd_id;
    private javax.swing.JTextField tfd_sid1;
    // End of variables declaration//GEN-END:variables
}
