/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package high_school;

import javax.swing.JOptionPane;

/**
 *
 * @author Adrian
 */
public class StudentPn extends javax.swing.JPanel {

    /**
     * Creates new form TeacherP
     */
    



    public StudentPn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lab_studentReg = new javax.swing.JLabel();
        lab_student = new javax.swing.JLabel();
        tfd_id = new javax.swing.JTextField();
        lab_Fname = new javax.swing.JLabel();
        tfd_Fname = new javax.swing.JTextField();
        lab_SLname = new javax.swing.JLabel();
        lab_dateHire = new javax.swing.JLabel();
        lab_day = new javax.swing.JLabel();
        tfd_day = new javax.swing.JTextField();
        lab_month = new javax.swing.JLabel();
        tfd_month = new javax.swing.JTextField();
        lab_year = new javax.swing.JLabel();
        tfd_year = new javax.swing.JTextField();
        lab_homePhone = new javax.swing.JLabel();
        tfd_homePhone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfd_mobilePhone = new javax.swing.JTextField();
        lab_discipline = new javax.swing.JLabel();
        tfd_address = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        tfd_Lname = new javax.swing.JTextField();
        lab_teacherId1 = new javax.swing.JLabel();
        tfd_teachId = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(600, 440));
        setMinimumSize(new java.awt.Dimension(600, 440));
        setPreferredSize(new java.awt.Dimension(600, 440));

        lab_studentReg.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lab_studentReg.setText("Student Registration:");

        lab_student.setBackground(new java.awt.Color(204, 204, 255));
        lab_student.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_student.setText("Student Id");
        lab_student.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_student.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_student.setPreferredSize(new java.awt.Dimension(80, 30));

        tfd_id.setMaximumSize(new java.awt.Dimension(80, 20));
        tfd_id.setMinimumSize(new java.awt.Dimension(80, 20));
        tfd_id.setPreferredSize(new java.awt.Dimension(80, 20));
        tfd_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_idActionPerformed(evt);
            }
        });

        lab_Fname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_Fname.setText("First Name");
        lab_Fname.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_Fname.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_Fname.setPreferredSize(new java.awt.Dimension(80, 30));

        tfd_Fname.setMaximumSize(new java.awt.Dimension(80, 20));
        tfd_Fname.setMinimumSize(new java.awt.Dimension(80, 20));
        tfd_Fname.setPreferredSize(new java.awt.Dimension(80, 20));
        tfd_Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_FnameActionPerformed(evt);
            }
        });

        lab_SLname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_SLname.setText("Last Name");
        lab_SLname.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_SLname.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_SLname.setPreferredSize(new java.awt.Dimension(80, 30));

        lab_dateHire.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_dateHire.setText("Date Hired");
        lab_dateHire.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_dateHire.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_dateHire.setPreferredSize(new java.awt.Dimension(80, 30));

        lab_day.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_day.setText("Day");
        lab_day.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_day.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_day.setPreferredSize(new java.awt.Dimension(80, 30));

        tfd_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_dayActionPerformed(evt);
            }
        });

        lab_month.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_month.setText("Month");
        lab_month.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_month.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_month.setPreferredSize(new java.awt.Dimension(80, 30));

        tfd_month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_monthActionPerformed(evt);
            }
        });

        lab_year.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_year.setText("Year");
        lab_year.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_year.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_year.setPreferredSize(new java.awt.Dimension(80, 30));

        tfd_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_yearActionPerformed(evt);
            }
        });

        lab_homePhone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_homePhone.setText(" Home Phone:");
        lab_homePhone.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_homePhone.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_homePhone.setPreferredSize(new java.awt.Dimension(80, 30));

        tfd_homePhone.setMaximumSize(new java.awt.Dimension(80, 20));
        tfd_homePhone.setMinimumSize(new java.awt.Dimension(80, 20));
        tfd_homePhone.setPreferredSize(new java.awt.Dimension(80, 20));
        tfd_homePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_homePhoneActionPerformed(evt);
            }
        });

        jLabel1.setText("Mobile Phone:");
        jLabel1.setMaximumSize(new java.awt.Dimension(80, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(80, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 30));

        tfd_mobilePhone.setMaximumSize(new java.awt.Dimension(80, 20));
        tfd_mobilePhone.setMinimumSize(new java.awt.Dimension(80, 20));
        tfd_mobilePhone.setPreferredSize(new java.awt.Dimension(80, 20));

        lab_discipline.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_discipline.setText("Address");
        lab_discipline.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_discipline.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_discipline.setPreferredSize(new java.awt.Dimension(80, 30));

        tfd_address.setMaximumSize(new java.awt.Dimension(80, 20));
        tfd_address.setMinimumSize(new java.awt.Dimension(80, 20));
        tfd_address.setPreferredSize(new java.awt.Dimension(80, 20));
        tfd_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_addressActionPerformed(evt);
            }
        });

        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        tfd_Lname.setMaximumSize(new java.awt.Dimension(80, 20));
        tfd_Lname.setMinimumSize(new java.awt.Dimension(80, 20));
        tfd_Lname.setPreferredSize(new java.awt.Dimension(80, 20));
        tfd_Lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_LnameActionPerformed(evt);
            }
        });

        lab_teacherId1.setBackground(new java.awt.Color(204, 204, 255));
        lab_teacherId1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_teacherId1.setText("Teacher ID");
        lab_teacherId1.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_teacherId1.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_teacherId1.setPreferredSize(new java.awt.Dimension(80, 30));

        tfd_teachId.setMaximumSize(new java.awt.Dimension(80, 20));
        tfd_teachId.setMinimumSize(new java.awt.Dimension(80, 20));
        tfd_teachId.setPreferredSize(new java.awt.Dimension(80, 20));
        tfd_teachId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_teachIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lab_studentReg, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(433, 433, 433))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(160, 160, 160))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(lab_teacherId1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tfd_teachId, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lab_discipline, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfd_address, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lab_dateHire, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lab_homePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lab_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lab_student, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfd_homePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lab_day, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfd_day, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfd_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfd_id, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lab_month, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfd_month, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(tfd_mobilePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lab_SLname, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lab_year, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfd_year, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfd_Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lab_studentReg, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_teacherId1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd_teachId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_student, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd_id, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfd_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_SLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd_Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_dateHire, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfd_homePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_homePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd_mobilePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lab_discipline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd_address, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_submit)
                    .addComponent(btn_cancel))
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents
        public void clearingText(){
        tfd_teachId.setText("");
        tfd_id.setText("");
        tfd_Fname.setText("");
         tfd_Lname.setText("");
          tfd_day.setText(""); 
          tfd_month.setText(""); 
          tfd_year.setText(""); 
           tfd_homePhone.setText("");
            tfd_mobilePhone.setText("");
            tfd_address.setText("");
        
    }

    public void studentRegistration(){

        String teachID=tfd_teachId.getText();
        int count= Student.count;
        
        int i;
        
        boolean correctTeacherID=false;
        
            for(i=0; i< Highschool.teacher_arr.length;i++){
            
                if(Highschool.teacher_arr[i] ==null);
                else{
                    if(Highschool.teacher_arr[i].getID().equals(teachID)){correctTeacherID=true;break; }
                     }   
                      
         }
        
        if(correctTeacherID==true){    
            int d= Integer.parseInt(tfd_day.getText());
            int m= Integer.parseInt(tfd_month.getText());
            int y= Integer.parseInt(tfd_year.getText());
            
            
                if(count>=10){
                 JOptionPane.showMessageDialog(this,"NO more students could be registered, Sorry!!");        
                }  
                else{
                 Highschool.student_arr[count] = new Student(tfd_id.getText(), tfd_Fname.getText(), tfd_Lname.getText(),
                 new Date (d,m,y),tfd_address.getText(),Highschool.teacher_arr[i],tfd_homePhone.getText(),tfd_mobilePhone.getText());
                     
                JOptionPane.showMessageDialog(this,"Student Sucessfully Registered");
                        clearingText();
                }
          } 
        else{  JOptionPane.showMessageDialog(this,"invalid teacher id");
       
        }
}
       
    
    private void tfd_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_yearActionPerformed

    private void tfd_monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_monthActionPerformed

    private void tfd_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_idActionPerformed

    private void tfd_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_dayActionPerformed

    private void tfd_FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_FnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_FnameActionPerformed

    private void tfd_homePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_homePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_homePhoneActionPerformed

    private void tfd_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_addressActionPerformed

    private void tfd_LnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_LnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_LnameActionPerformed

    private void tfd_teachIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_teachIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_teachIdActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
 studentRegistration();
 
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        clearingText();
    }//GEN-LAST:event_btn_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lab_Fname;
    private javax.swing.JLabel lab_SLname;
    private javax.swing.JLabel lab_dateHire;
    private javax.swing.JLabel lab_day;
    private javax.swing.JLabel lab_discipline;
    private javax.swing.JLabel lab_homePhone;
    private javax.swing.JLabel lab_month;
    private javax.swing.JLabel lab_student;
    private javax.swing.JLabel lab_studentReg;
    private javax.swing.JLabel lab_teacherId1;
    private javax.swing.JLabel lab_year;
    private javax.swing.JTextField tfd_Fname;
    private javax.swing.JTextField tfd_Lname;
    private javax.swing.JTextField tfd_address;
    private javax.swing.JTextField tfd_day;
    private javax.swing.JTextField tfd_homePhone;
    private javax.swing.JTextField tfd_id;
    private javax.swing.JTextField tfd_mobilePhone;
    private javax.swing.JTextField tfd_month;
    private javax.swing.JTextField tfd_teachId;
    private javax.swing.JTextField tfd_year;
    // End of variables declaration//GEN-END:variables
}
