/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package high_school;

import javax.swing.JOptionPane;

/**
 *
 * @author Adrian
 */
public class TeacherP extends javax.swing.JPanel {

    /**
     * Creates new form TeacherP
     */

    
    public TeacherP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lab_studentReg = new javax.swing.JLabel();
        lab_teacherId = new javax.swing.JLabel();
        tfd_tid = new javax.swing.JTextField();
        lab_Fname = new javax.swing.JLabel();
        tfd_Fname = new javax.swing.JTextField();
        lab_SLname = new javax.swing.JLabel();
        lab_dateHire = new javax.swing.JLabel();
        lab_day = new javax.swing.JLabel();
        tfd_day = new javax.swing.JTextField();
        lab_month = new javax.swing.JLabel();
        tfd_month = new javax.swing.JTextField();
        lab_year = new javax.swing.JLabel();
        tfd_year = new javax.swing.JTextField();
        lab_homePhone = new javax.swing.JLabel();
        tfd_homePhone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfd_mobilePhone = new javax.swing.JTextField();
        lab_discipline = new javax.swing.JLabel();
        tfd_discipline = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        tfd_Lname = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(600, 440));
        setMinimumSize(new java.awt.Dimension(600, 440));
        setPreferredSize(new java.awt.Dimension(600, 440));

        lab_studentReg.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lab_studentReg.setText("Teacher Registration:");

        lab_teacherId.setBackground(new java.awt.Color(204, 204, 255));
        lab_teacherId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_teacherId.setText("Teacher ID");
        lab_teacherId.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_teacherId.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_teacherId.setPreferredSize(new java.awt.Dimension(80, 30));

        tfd_tid.setMaximumSize(new java.awt.Dimension(80, 20));
        tfd_tid.setMinimumSize(new java.awt.Dimension(80, 20));
        tfd_tid.setPreferredSize(new java.awt.Dimension(80, 20));
        tfd_tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_tidActionPerformed(evt);
            }
        });

        lab_Fname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_Fname.setText("First Name");
        lab_Fname.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_Fname.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_Fname.setPreferredSize(new java.awt.Dimension(80, 30));

        tfd_Fname.setMaximumSize(new java.awt.Dimension(80, 20));
        tfd_Fname.setMinimumSize(new java.awt.Dimension(80, 20));
        tfd_Fname.setPreferredSize(new java.awt.Dimension(80, 20));
        tfd_Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_FnameActionPerformed(evt);
            }
        });

        lab_SLname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_SLname.setText("Last Name");
        lab_SLname.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_SLname.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_SLname.setPreferredSize(new java.awt.Dimension(80, 30));

        lab_dateHire.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_dateHire.setText("Date Hired");
        lab_dateHire.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_dateHire.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_dateHire.setPreferredSize(new java.awt.Dimension(80, 30));

        lab_day.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_day.setText("Day");
        lab_day.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_day.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_day.setPreferredSize(new java.awt.Dimension(80, 30));

        tfd_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_dayActionPerformed(evt);
            }
        });

        lab_month.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_month.setText("Month");
        lab_month.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_month.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_month.setPreferredSize(new java.awt.Dimension(80, 30));

        tfd_month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_monthActionPerformed(evt);
            }
        });

        lab_year.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_year.setText("Year");
        lab_year.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_year.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_year.setPreferredSize(new java.awt.Dimension(80, 30));

        tfd_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_yearActionPerformed(evt);
            }
        });

        lab_homePhone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_homePhone.setText(" Home Phone:");
        lab_homePhone.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_homePhone.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_homePhone.setPreferredSize(new java.awt.Dimension(80, 30));

        tfd_homePhone.setMaximumSize(new java.awt.Dimension(80, 20));
        tfd_homePhone.setMinimumSize(new java.awt.Dimension(80, 20));
        tfd_homePhone.setPreferredSize(new java.awt.Dimension(80, 20));
        tfd_homePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_homePhoneActionPerformed(evt);
            }
        });

        jLabel1.setText("Mobile Phone:");
        jLabel1.setMaximumSize(new java.awt.Dimension(80, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(80, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 30));

        tfd_mobilePhone.setMaximumSize(new java.awt.Dimension(80, 20));
        tfd_mobilePhone.setMinimumSize(new java.awt.Dimension(80, 20));
        tfd_mobilePhone.setPreferredSize(new java.awt.Dimension(80, 20));

        lab_discipline.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lab_discipline.setText("Discipline");
        lab_discipline.setMaximumSize(new java.awt.Dimension(80, 30));
        lab_discipline.setMinimumSize(new java.awt.Dimension(80, 30));
        lab_discipline.setPreferredSize(new java.awt.Dimension(80, 30));

        tfd_discipline.setMaximumSize(new java.awt.Dimension(80, 20));
        tfd_discipline.setMinimumSize(new java.awt.Dimension(80, 20));
        tfd_discipline.setPreferredSize(new java.awt.Dimension(80, 20));
        tfd_discipline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_disciplineActionPerformed(evt);
            }
        });

        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        tfd_Lname.setMaximumSize(new java.awt.Dimension(80, 20));
        tfd_Lname.setMinimumSize(new java.awt.Dimension(80, 20));
        tfd_Lname.setPreferredSize(new java.awt.Dimension(80, 20));
        tfd_Lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_LnameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lab_studentReg, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lab_homePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfd_homePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfd_mobilePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lab_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lab_teacherId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lab_dateHire, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lab_day, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tfd_day, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(12, 12, 12)
                                            .addComponent(lab_month, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tfd_month, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lab_year, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(tfd_year, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tfd_Fname, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                                .addComponent(tfd_tid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(10, 10, 10)
                                            .addComponent(lab_SLname, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(tfd_Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(146, 146, 146))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lab_discipline, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfd_discipline, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lab_studentReg, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lab_teacherId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(tfd_tid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lab_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lab_SLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfd_Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(tfd_Fname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lab_dateHire, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lab_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lab_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfd_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lab_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfd_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfd_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfd_mobilePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lab_homePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(tfd_homePhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lab_discipline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd_discipline, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_submit)
                    .addComponent(btn_cancel))
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfd_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_yearActionPerformed

    private void tfd_monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_monthActionPerformed

    private void tfd_tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_tidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_tidActionPerformed

    private void tfd_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_dayActionPerformed

    private void tfd_FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_FnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_FnameActionPerformed

    private void tfd_homePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_homePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_homePhoneActionPerformed

    private void tfd_disciplineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_disciplineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_disciplineActionPerformed

    private void tfd_LnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_LnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd_LnameActionPerformed
    public void clearingText(){
        tfd_tid.setText("");
        tfd_Fname.setText("");
         tfd_Lname.setText("");
          tfd_day.setText(""); 
          tfd_month.setText(""); 
          tfd_year.setText(""); 
          tfd_discipline.setText("");
           tfd_homePhone.setText("");
            tfd_mobilePhone.setText("");
        
    }
    
    public void teacherRegistration(){
        

        
        int count= Teacher.Tcount;
            
            int d= Integer.parseInt(tfd_day.getText());
            int m= Integer.parseInt(tfd_month.getText());
            int y= Integer.parseInt(tfd_year.getText());
            
            
                if(count>=4){
                 JOptionPane.showMessageDialog(this,"NO more teachers could be registered, Sorry!!");        
                }  
                else{
                 Highschool.teacher_arr[count] = new Teacher(tfd_tid.getText(), tfd_Fname.getText(), tfd_Lname.getText(),
                 new Date (d,m,y),tfd_discipline.getText(),tfd_homePhone.getText(),tfd_mobilePhone.getText());
                     
                JOptionPane.showMessageDialog(this,"Teacher Sucessfully Registered");
                clearingText();    
                }
                
                 }
    
    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
       teacherRegistration();
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
       clearingText(); 
    }//GEN-LAST:event_btn_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lab_Fname;
    private javax.swing.JLabel lab_SLname;
    private javax.swing.JLabel lab_dateHire;
    private javax.swing.JLabel lab_day;
    private javax.swing.JLabel lab_discipline;
    private javax.swing.JLabel lab_homePhone;
    private javax.swing.JLabel lab_month;
    private javax.swing.JLabel lab_studentReg;
    private javax.swing.JLabel lab_teacherId;
    private javax.swing.JLabel lab_year;
    private javax.swing.JTextField tfd_Fname;
    private javax.swing.JTextField tfd_Lname;
    private javax.swing.JTextField tfd_day;
    private javax.swing.JTextField tfd_discipline;
    private javax.swing.JTextField tfd_homePhone;
    private javax.swing.JTextField tfd_mobilePhone;
    private javax.swing.JTextField tfd_month;
    private javax.swing.JTextField tfd_tid;
    private javax.swing.JTextField tfd_year;
    // End of variables declaration//GEN-END:variables
}
